apiVersion: v1
kind: Secret
metadata:
  name: email-secret
type: Opaque
data:
  SPRING_MAIL_HOST: c210cC5nbWFpbC5jb20=
  SPRING_MAIL_PORT: NTg3
  SPRING_MAIL_USERNAME: dGgzbS50aGVtQGdtYWlsLmNvbQ==
  SPRING_MAIL_PASSWORD: Y2tvbmlkc2d0YnlsYWtoaA==